{
  "hosts": [
    {
      "hostname" : "tp.seerene.com",
      "http" : {
        "timeout" : 2,
        "port" :    80,
        "ssl" : true
      }
    },
    {
      "hostname" : "bbc.co.uk",
      "icmp" : {
        "enable" : true,
        "timeout" : 1
      },
      "http" : {
        "enable" : true,
        "timeout" : 2,
        "port" : 88,
        "ssl" : true
      }
    },
    {
      "hostname" : "wp.pl",
      "icmp" : {
        "enable" : true,
        "timeout" : 1
      },
      "http" : {
        "enable" : true,
        "timeout" : 2,
        "port" : 80,
        "ssl" : true
      }
    },
    {
      "hostname" : "212.77.98.9",
      "icmp" : {
        "enable" : true,
        "timeout" : 1
      }
    }
  ]
}
